apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgappdb-deployment
  namespace: bgapp-db
  labels:
    app: bgapp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgapp
  template:
    metadata:
      labels:
        app: bgapp-db
    spec:
      containers:
        - name: bgapp-db
          image: stoimenovrado/bgapp-db
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: '12345'
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
