apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgapp-deployment
  labels:
    app: bgapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgapp
  template:
    metadata:
      labels:
        app: bgapp
    spec:
      containers:
      - name: bgapp
        image: stoimenovrado/bgapp-web
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        env:
          - name: DB_HOST
            value: bgappdb-service
          - name: DB_PORT
            value: "3306"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
